# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T01:45:16+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class FlexrsGoal(Enum):
    FLEXRS_UNSPECIFIED = 'FLEXRS_UNSPECIFIED'
    FLEXRS_SPEED_OPTIMIZED = 'FLEXRS_SPEED_OPTIMIZED'
    FLEXRS_COST_OPTIMIZED = 'FLEXRS_COST_OPTIMIZED'


class IpConfiguration(Enum):
    WORKER_IP_UNSPECIFIED = 'WORKER_IP_UNSPECIFIED'
    WORKER_IP_PUBLIC = 'WORKER_IP_PUBLIC'
    WORKER_IP_PRIVATE = 'WORKER_IP_PRIVATE'


class GoogleCloudDatapipelinesV1FlexTemplateRuntimeEnvironment(BaseModel):
    additionalExperiments: Optional[List[str]] = Field(
        None, description='Additional experiment flags for the job.'
    )
    additionalUserLabels: Optional[Dict[str, str]] = Field(
        None,
        description='Additional user labels to be specified for the job. Keys and values must follow the restrictions specified in the [labeling restrictions](https://cloud.google.com/compute/docs/labeling-resources#restrictions). An object containing a list of key/value pairs. Example: `{ "name": "wrench", "mass": "1kg", "count": "3" }`.',
    )
    enableStreamingEngine: Optional[bool] = Field(
        None, description='Whether to enable Streaming Engine for the job.'
    )
    flexrsGoal: Optional[FlexrsGoal] = Field(
        None,
        description='Set FlexRS goal for the job. https://cloud.google.com/dataflow/docs/guides/flexrs',
    )
    ipConfiguration: Optional[IpConfiguration] = Field(
        None, description='Configuration for VM IPs.'
    )
    kmsKeyName: Optional[str] = Field(
        None,
        description='Name for the Cloud KMS key for the job. Key format is: projects//locations//keyRings//cryptoKeys/',
    )
    machineType: Optional[str] = Field(
        None,
        description='The machine type to use for the job. Defaults to the value from the template if not specified.',
    )
    maxWorkers: Optional[int] = Field(
        None,
        description='The maximum number of Compute Engine instances to be made available to your pipeline during execution, from 1 to 1000.',
    )
    network: Optional[str] = Field(
        None,
        description='Network to which VMs will be assigned. If empty or unspecified, the service will use the network "default".',
    )
    numWorkers: Optional[int] = Field(
        None, description='The initial number of Compute Engine instances for the job.'
    )
    serviceAccountEmail: Optional[str] = Field(
        None, description='The email address of the service account to run the job as.'
    )
    subnetwork: Optional[str] = Field(
        None,
        description='Subnetwork to which VMs will be assigned, if desired. You can specify a subnetwork using either a complete URL or an abbreviated path. Expected to be of the form "https://www.googleapis.com/compute/v1/projects/HOST_PROJECT_ID/regions/REGION/subnetworks/SUBNETWORK" or "regions/REGION/subnetworks/SUBNETWORK". If the subnetwork is located in a Shared VPC network, you must use the complete URL.',
    )
    tempLocation: Optional[str] = Field(
        None,
        description='The Cloud Storage path to use for temporary files. Must be a valid Cloud Storage URL, beginning with `gs://`.',
    )
    workerRegion: Optional[str] = Field(
        None,
        description='The Compute Engine region (https://cloud.google.com/compute/docs/regions-zones/regions-zones) in which worker processing should occur, e.g. "us-west1". Mutually exclusive with worker_zone. If neither worker_region nor worker_zone is specified, defaults to the control plane region.',
    )
    workerZone: Optional[str] = Field(
        None,
        description='The Compute Engine zone (https://cloud.google.com/compute/docs/regions-zones/regions-zones) in which worker processing should occur, e.g. "us-west1-a". Mutually exclusive with worker_region. If neither worker_region nor worker_zone is specified, a zone in the control plane region is chosen based on available capacity. If both `worker_zone` and `zone` are set, `worker_zone` takes precedence.',
    )
    zone: Optional[str] = Field(
        None,
        description='The Compute Engine [availability zone](https://cloud.google.com/compute/docs/regions-zones/regions-zones) for launching worker instances to run your pipeline. In the future, worker_zone will take precedence.',
    )


class State(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    STATE_PENDING = 'STATE_PENDING'
    STATE_RUNNING = 'STATE_RUNNING'
    STATE_DONE = 'STATE_DONE'
    STATE_FAILED = 'STATE_FAILED'
    STATE_CANCELLED = 'STATE_CANCELLED'


class GoogleCloudDatapipelinesV1LaunchFlexTemplateParameter(BaseModel):
    containerSpecGcsPath: Optional[str] = Field(
        None,
        description='Cloud Storage path to a file with a JSON-serialized ContainerSpec as content.',
    )
    environment: Optional[GoogleCloudDatapipelinesV1FlexTemplateRuntimeEnvironment] = (
        Field(None, description='The runtime environment for the Flex Template job.')
    )
    jobName: Optional[str] = Field(
        None,
        description='Required. The job name to use for the created job. For an update job request, the job name should be the same as the existing running job.',
    )
    launchOptions: Optional[Dict[str, str]] = Field(
        None,
        description='Launch options for this Flex Template job. This is a common set of options across languages and templates. This should not be used to pass job parameters.',
    )
    parameters: Optional[Dict[str, str]] = Field(
        None,
        description='The parameters for the Flex Template. Example: `{"num_workers":"5"}`',
    )
    transformNameMappings: Optional[Dict[str, str]] = Field(
        None,
        description='Use this to pass transform name mappings for streaming update jobs. Example: `{"oldTransformName":"newTransformName",...}`',
    )
    update: Optional[bool] = Field(
        None,
        description='Set this to true if you are sending a request to update a running streaming job. When set, the job name should be the same as the running job.',
    )


class GoogleCloudDatapipelinesV1LaunchFlexTemplateRequest(BaseModel):
    launchParameter: Optional[GoogleCloudDatapipelinesV1LaunchFlexTemplateParameter] = (
        Field(
            None,
            description='Required. Parameter to launch a job from a Flex Template.',
        )
    )
    location: Optional[str] = Field(
        None,
        description='Required. The [regional endpoint] (https://cloud.google.com/dataflow/docs/concepts/regional-endpoints) to which to direct the request. For example, `us-central1`, `us-west1`.',
    )
    projectId: Optional[str] = Field(
        None,
        description='Required. The ID of the Cloud Platform project that the job belongs to.',
    )
    validateOnly: Optional[bool] = Field(
        None,
        description='If true, the request is validated but not actually executed. Defaults to false.',
    )


class State1(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    STATE_RESUMING = 'STATE_RESUMING'
    STATE_ACTIVE = 'STATE_ACTIVE'
    STATE_STOPPING = 'STATE_STOPPING'
    STATE_ARCHIVED = 'STATE_ARCHIVED'
    STATE_PAUSED = 'STATE_PAUSED'


class Type(Enum):
    PIPELINE_TYPE_UNSPECIFIED = 'PIPELINE_TYPE_UNSPECIFIED'
    PIPELINE_TYPE_BATCH = 'PIPELINE_TYPE_BATCH'
    PIPELINE_TYPE_STREAMING = 'PIPELINE_TYPE_STREAMING'


class GoogleCloudDatapipelinesV1RunPipelineRequest(BaseModel):
    pass


class GoogleCloudDatapipelinesV1RuntimeEnvironment(BaseModel):
    additionalExperiments: Optional[List[str]] = Field(
        None, description='Additional experiment flags for the job.'
    )
    additionalUserLabels: Optional[Dict[str, str]] = Field(
        None,
        description='Additional user labels to be specified for the job. Keys and values should follow the restrictions specified in the [labeling restrictions](https://cloud.google.com/compute/docs/labeling-resources#restrictions) page. An object containing a list of key/value pairs. Example: { "name": "wrench", "mass": "1kg", "count": "3" }.',
    )
    bypassTempDirValidation: Optional[bool] = Field(
        None,
        description="Whether to bypass the safety checks for the job's temporary directory. Use with caution.",
    )
    enableStreamingEngine: Optional[bool] = Field(
        None, description='Whether to enable Streaming Engine for the job.'
    )
    ipConfiguration: Optional[IpConfiguration] = Field(
        None, description='Configuration for VM IPs.'
    )
    kmsKeyName: Optional[str] = Field(
        None,
        description='Name for the Cloud KMS key for the job. The key format is: projects//locations//keyRings//cryptoKeys/',
    )
    machineType: Optional[str] = Field(
        None,
        description='The machine type to use for the job. Defaults to the value from the template if not specified.',
    )
    maxWorkers: Optional[int] = Field(
        None,
        description='The maximum number of Compute Engine instances to be made available to your pipeline during execution, from 1 to 1000.',
    )
    network: Optional[str] = Field(
        None,
        description='Network to which VMs will be assigned. If empty or unspecified, the service will use the network "default".',
    )
    numWorkers: Optional[int] = Field(
        None, description='The initial number of Compute Engine instances for the job.'
    )
    serviceAccountEmail: Optional[str] = Field(
        None, description='The email address of the service account to run the job as.'
    )
    subnetwork: Optional[str] = Field(
        None,
        description='Subnetwork to which VMs will be assigned, if desired. You can specify a subnetwork using either a complete URL or an abbreviated path. Expected to be of the form "https://www.googleapis.com/compute/v1/projects/HOST_PROJECT_ID/regions/REGION/subnetworks/SUBNETWORK" or "regions/REGION/subnetworks/SUBNETWORK". If the subnetwork is located in a Shared VPC network, you must use the complete URL.',
    )
    tempLocation: Optional[str] = Field(
        None,
        description='The Cloud Storage path to use for temporary files. Must be a valid Cloud Storage URL, beginning with `gs://`.',
    )
    workerRegion: Optional[str] = Field(
        None,
        description='The Compute Engine region (https://cloud.google.com/compute/docs/regions-zones/regions-zones) in which worker processing should occur, e.g. "us-west1". Mutually exclusive with worker_zone. If neither worker_region nor worker_zone is specified, default to the control plane\'s region.',
    )
    workerZone: Optional[str] = Field(
        None,
        description='The Compute Engine zone (https://cloud.google.com/compute/docs/regions-zones/regions-zones) in which worker processing should occur, e.g. "us-west1-a". Mutually exclusive with worker_region. If neither worker_region nor worker_zone is specified, a zone in the control plane\'s region is chosen based on available capacity. If both `worker_zone` and `zone` are set, `worker_zone` takes precedence.',
    )
    zone: Optional[str] = Field(
        None,
        description='The Compute Engine [availability zone](https://cloud.google.com/compute/docs/regions-zones/regions-zones) for launching worker instances to run your pipeline. In the future, worker_zone will take precedence.',
    )


class GoogleCloudDatapipelinesV1ScheduleSpec(BaseModel):
    nextJobTime: Optional[str] = Field(
        None, description='Output only. When the next Scheduler job is going to run.'
    )
    schedule: Optional[str] = Field(
        None,
        description='Unix-cron format of the schedule. This information is retrieved from the linked Cloud Scheduler.',
    )
    timeZone: Optional[str] = Field(
        None,
        description='Timezone ID. This matches the timezone IDs used by the Cloud Scheduler API. If empty, UTC time is assumed.',
    )


class SdkSupportStatus(Enum):
    UNKNOWN = 'UNKNOWN'
    SUPPORTED = 'SUPPORTED'
    STALE = 'STALE'
    DEPRECATED = 'DEPRECATED'
    UNSUPPORTED = 'UNSUPPORTED'


class GoogleCloudDatapipelinesV1SdkVersion(BaseModel):
    sdkSupportStatus: Optional[SdkSupportStatus] = Field(
        None, description='The support status for this SDK version.'
    )
    version: Optional[str] = Field(
        None, description='The version of the SDK used to run the job.'
    )
    versionDisplayName: Optional[str] = Field(
        None, description='A readable string describing the version of the SDK.'
    )


class GoogleCloudDatapipelinesV1StopPipelineRequest(BaseModel):
    pass


class GoogleProtobufEmpty(BaseModel):
    pass


class GoogleRpcStatus(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class GoogleCloudDatapipelinesV1DataflowJobDetails(BaseModel):
    currentWorkers: Optional[int] = Field(
        None,
        description='Output only. The current number of workers used to run the jobs. Only set to a value if the job is still running.',
    )
    resourceInfo: Optional[Dict[str, float]] = Field(
        None,
        description='Cached version of all the metrics of interest for the job. This value gets stored here when the job is terminated. As long as the job is running, this field is populated from the Dataflow API.',
    )
    sdkVersion: Optional[GoogleCloudDatapipelinesV1SdkVersion] = Field(
        None, description='Output only. The SDK version used to run the job.'
    )


class GoogleCloudDatapipelinesV1Job(BaseModel):
    createTime: Optional[str] = Field(
        None, description='Output only. The time of job creation.'
    )
    dataflowJobDetails: Optional[GoogleCloudDatapipelinesV1DataflowJobDetails] = Field(
        None, description='All the details that are specific to a Dataflow job.'
    )
    endTime: Optional[str] = Field(
        None,
        description='Output only. The time of job termination. This is absent if the job is still running.',
    )
    id: Optional[str] = Field(
        None, description='Output only. The internal ID for the job.'
    )
    name: Optional[str] = Field(
        None, description='Required. The fully qualified resource name for the job.'
    )
    state: Optional[State] = Field(None, description='The current state of the job.')
    status: Optional[GoogleRpcStatus] = Field(
        None,
        description='Status capturing any error code or message related to job creation or execution.',
    )


class GoogleCloudDatapipelinesV1LaunchTemplateParameters(BaseModel):
    environment: Optional[GoogleCloudDatapipelinesV1RuntimeEnvironment] = Field(
        None, description='The runtime environment for the job.'
    )
    jobName: Optional[str] = Field(
        None, description='Required. The job name to use for the created job.'
    )
    parameters: Optional[Dict[str, str]] = Field(
        None, description='The runtime parameters to pass to the job.'
    )
    transformNameMapping: Optional[Dict[str, str]] = Field(
        None,
        description='Map of transform name prefixes of the job to be replaced to the corresponding name prefixes of the new job. Only applicable when updating a pipeline.',
    )
    update: Optional[bool] = Field(
        None,
        description='If set, replace the existing pipeline with the name specified by jobName with this pipeline, preserving state.',
    )


class GoogleCloudDatapipelinesV1LaunchTemplateRequest(BaseModel):
    gcsPath: Optional[str] = Field(
        None,
        description="A Cloud Storage path to the template from which to create the job. Must be a valid Cloud Storage URL, beginning with 'gs://'.",
    )
    launchParameters: Optional[GoogleCloudDatapipelinesV1LaunchTemplateParameters] = (
        Field(
            None,
            description='The parameters of the template to launch. This should be part of the body of the POST request.',
        )
    )
    location: Optional[str] = Field(
        None,
        description='The [regional endpoint] (https://cloud.google.com/dataflow/docs/concepts/regional-endpoints) to which to direct the request.',
    )
    projectId: Optional[str] = Field(
        None,
        description='Required. The ID of the Cloud Platform project that the job belongs to.',
    )
    validateOnly: Optional[bool] = Field(
        None,
        description='If true, the request is validated but not actually executed. Defaults to false.',
    )


class GoogleCloudDatapipelinesV1ListJobsResponse(BaseModel):
    jobs: Optional[List[GoogleCloudDatapipelinesV1Job]] = Field(
        None,
        description='Results that were accessible to the caller. Results are always in descending order of job creation date.',
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )


class GoogleCloudDatapipelinesV1RunPipelineResponse(BaseModel):
    job: Optional[GoogleCloudDatapipelinesV1Job] = Field(
        None, description='Job that was created as part of RunPipeline operation.'
    )


class GoogleCloudDatapipelinesV1Workload(BaseModel):
    dataflowFlexTemplateRequest: Optional[
        GoogleCloudDatapipelinesV1LaunchFlexTemplateRequest
    ] = Field(
        None,
        description='Template information and additional parameters needed to launch a Dataflow job using the flex launch API.',
    )
    dataflowLaunchTemplateRequest: Optional[
        GoogleCloudDatapipelinesV1LaunchTemplateRequest
    ] = Field(
        None,
        description='Template information and additional parameters needed to launch a Dataflow job using the standard launch API.',
    )


class GoogleCloudDatapipelinesV1Pipeline(BaseModel):
    createTime: Optional[str] = Field(
        None,
        description='Output only. Immutable. The timestamp when the pipeline was initially created. Set by the Data Pipelines service.',
    )
    displayName: Optional[str] = Field(
        None,
        description='Required. The display name of the pipeline. It can contain only letters ([A-Za-z]), numbers ([0-9]), hyphens (-), and underscores (_).',
    )
    jobCount: Optional[int] = Field(None, description='Output only. Number of jobs.')
    lastUpdateTime: Optional[str] = Field(
        None,
        description='Output only. Immutable. The timestamp when the pipeline was last modified. Set by the Data Pipelines service.',
    )
    name: Optional[str] = Field(
        None,
        description="The pipeline name. For example: `projects/PROJECT_ID/locations/LOCATION_ID/pipelines/PIPELINE_ID`. * `PROJECT_ID` can contain letters ([A-Za-z]), numbers ([0-9]), hyphens (-), colons (:), and periods (.). For more information, see [Identifying projects](https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects). * `LOCATION_ID` is the canonical ID for the pipeline's location. The list of available locations can be obtained by calling `google.cloud.location.Locations.ListLocations`. Note that the Data Pipelines service is not available in all regions. It depends on Cloud Scheduler, an App Engine application, so it's only available in [App Engine regions](https://cloud.google.com/about/locations#region). * `PIPELINE_ID` is the ID of the pipeline. Must be unique for the selected project and location.",
    )
    pipelineSources: Optional[Dict[str, str]] = Field(
        None,
        description='Immutable. The sources of the pipeline (for example, Dataplex). The keys and values are set by the corresponding sources during pipeline creation.',
    )
    scheduleInfo: Optional[GoogleCloudDatapipelinesV1ScheduleSpec] = Field(
        None,
        description='Internal scheduling information for a pipeline. If this information is provided, periodic jobs will be created per the schedule. If not, users are responsible for creating jobs externally.',
    )
    schedulerServiceAccountEmail: Optional[str] = Field(
        None,
        description='Optional. A service account email to be used with the Cloud Scheduler job. If not specified, the default compute engine service account will be used.',
    )
    state: Optional[State1] = Field(
        None,
        description="Required. The state of the pipeline. When the pipeline is created, the state is set to 'PIPELINE_STATE_ACTIVE' by default. State changes can be requested by setting the state to stopping, paused, or resuming. State cannot be changed through UpdatePipeline requests.",
    )
    type: Optional[Type] = Field(
        None,
        description='Required. The type of the pipeline. This field affects the scheduling of the pipeline and the type of metrics to show for the pipeline.',
    )
    workload: Optional[GoogleCloudDatapipelinesV1Workload] = Field(
        None, description='Workload information for creating new jobs.'
    )


class GoogleCloudDatapipelinesV1ListPipelinesResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is omitted, there are no subsequent pages.',
    )
    pipelines: Optional[List[GoogleCloudDatapipelinesV1Pipeline]] = Field(
        None,
        description='Results that matched the filter criteria and were accessible to the caller. Results are always in descending order of pipeline creation date.',
    )
